include: package:lint/analysis_options_package.yaml

linter:
  rules:
    - parameter_assignments
    
analyzer:
  # enable-experiment:
  #   - non-nullable
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    must_be_immutable: error
    public_member_api_docs: error
    package_api_docs: error
