name: flutter_gsuite
description: Flutter package to interact with Gsuite (GoogleAPIs) resources
version: 0.0.1+1
author: Enrique Velasco

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  extension_google_sign_in_as_googleapis_auth: ^1.0.1
  firebase_auth: ^0.18.4+1
  flamingo: ^1.13.0
  flamingo_annotation: ^0.4.0
  freezed_annotation: ^0.12.0
  google_sign_in: ^4.5.6
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  hive: ^1.4.4
  observable_ish: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  flamingo_generator: ^0.8.0
  freezed: ^0.12.6
  hive_generator: ^0.8.2
  lint: ^1.2.0

flutter: null
