name: rx_hive_cache
description: Reactive cache that works with Hive
version: 0.0.1+1
author: Enrique Velasco

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  hive: ^1.4.4+1
  observable_ish: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter: null
