name: rx_hive_cache
description: Reactive cache that works with Hive
version: 0.0.2
author: Enrique Velasco

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.1
  hive: ^2.0.1
  observable_ish: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter: null
